INSERT INTO lesson_notes_region(id, region_name)
VALUES
(1, 'Ahafo Region'),
(2, 'Ashanti Region'),
(3, 'Oti Region'),
(4, 'Bono Region'),
(5, 'Bono East Region'),
(6, 'Central Region'),
(7, 'Eastern Region'),
(8, 'Greater Accra Region'),
(9, 'Northern Region'),
(10, 'North East Region'),
(11, 'Savannah Region'),
(12, 'Upper East Region'),
(13, 'Upper West Region'),
(14, 'Volta Region'),
(15, 'Western Region'),
(16, 'Western North Region');

INSERT INTO lesson_notes_district(district_name, region_id)
VALUES
('Asunafo North Municipal', 1),
('Asunafo South', 1),
('Asutifi North', 1),
('Asutifi South', 1),
('Tano North Municipal', 1),
('Tano South Municipal', 1),
('Adansi Asokwa', 2),
('Adansi North', 2),
('Adansi South', 2),
('Afigya Kwabre North', 2),
('Afigya Kwabre South', 2),
('Ahafo Ano North Municipal', 2),
('Ahafo Ano South East', 2),
('Ahafo Ano South West', 2),
('Akrofuom', 2),
('Amansie Central', 2),
('Amansie West', 2),
('Amansie South', 2),
('Asante Akim Central Municipal', 2),
('Asante Akim North', 2),
('Asante Akim South Municipal', 2),
('Asokore Mampong', 2),
('Asokwa Municipal', 2),
('Atwima Kwanwoma', 2),
('Atwima Mponua', 2),
('Atwima Nwabiagya Municipal', 2),
('Atwima Nwabiagya North', 2),
('Bekwai Municipal', 2),
('Bosome Freho', 2),
('Bosomtwe', 2),
('Ejisu Municipal', 2),
('Ejura Sekyedumase Municipal', 2),
('Juaben Municipal', 2),
('Kumasi Metropolitan', 2),
('Manhyia North', 2),
('Manhyia South', 2),
('Nhyiaeso', 2),
('Subin', 2),
('Kwabre East Municipal', 2),
('Kwadaso Municipal', 2),
('Mampong Municipal', 2),
('Obuasi East Municipal', 2),
('Obuasi Municipal', 2),
('Offinso Municipal', 2),
('Offinso North', 2),
('Oforikrom Municipal', 2),
('Old Tafo Municipal', 2),
('Sekyere Afram Plains', 2),
('Sekyere Central', 2),
('Sekyere East', 2),
('Sekyere Kumawu', 2),
('Sekyere South', 2),
('Suame Municipal', 2),
('Biakoye', 3),
('Jasikan', 3),
('Kadjebi', 3),
('Krachi East Municipal', 3),
('Krachi Nchumuru', 3),
('Krachi West', 3),
('Nkwanta North', 3),
('Nkwanta South Municipal', 3),
('Banda', 4),
('Berekum East Municipal', 4),
('Berekum West', 4),
('Dormaa Central Municipal', 4),
('Dormaa East District', 4),
('Dormaa West', 4),
('Jaman North', 4),
('Jaman South Municipal', 4),
('Sunyani Municipal', 4),
('Sunyani West', 4),
('Tain', 4),
('Wenchi Municipal', 4),
('Atebubu-Amantin Municipal', 5),
('Kintampo North Municipal', 5),
('Kintampo South', 5),
('Nkoranza North', 5),
('Nkoranza South Municipal', 5),
('Pru East', 5),
('Pru West', 5),
('Sene East', 5),
('Sene West', 5),
('Techiman Municipal', 5),
('Techiman North', 5),
('Abura Asebu Kwamankese', 6),
('Agona East', 6),
('Agona West Municipal', 6),
('Ajumako Enyan Essiam', 6),
('Asikuma Odoben Brakwa', 6),
('Assin Central Municipal', 6),
('Assin North', 6),
('Assin South',6),
('Awutu Senya East Municipal', 6),
('Awutu Senya West', 6),
('Cape Coast Metropolitan', 6),
('Cape Coast South', 6),
('Effutu Municipal', 6),
('Ekumfi', 6),
('Gomoa East', 6),
('Gomoa Central', 6),
('Gomoa West',6),
('Komenda-Edina-Eguafo-Abirem Municipal', 6),
('Mfantsiman Municipal', 6),
('Twifo Atti Morkwa', 6),
('Twifo/Heman/Lower Denkyira', 6),
('Upper Denkyira East Municipal', 6),
('Upper Denkyira West', 6),
('Abuakwa North Municipal', 7),
('Abuakwa South Municipal', 7),
('Achiase', 7),
('Akuapim North Municipal',7),
('Akuapim South', 7),
('Akyemansa', 7),
('Asene Manso Akroso', 7),
('Asuogyaman', 7),
('Atiwa East', 7),
('Atiwa West', 7),
('Ayensuano', 7),
('Birim Central Municipal', 7),
('Birim North',7),
('Birim South',7),
('Denkyembour', 7),
('Fanteakwa North', 7),
('Fanteakwa South', 7),
('Kwaebibirem Municipal', 7),
('Kwahu Afram Plains North', 7),
('Kwahu Afram Plains South', 7),
('Kwahu East', 7),
('Kwahu South', 7),
('Kwahu West Municipal', 7),
('Lower Manya Krobo Municipal', 7),
('New Juaben North Municipal', 7),
('New Juaben South Municipal', 7),
('Nsawam Adoagyire Municipal', 7),
('Okere', 7),
('Suhum Municipal', 7),
('Upper Manya Krobo',7),
('Upper West Akim', 7),
('West Akim Municipal', 7),
('Yilo Krobo Municipal', 7),
('Ablekuma Central Municipal', 8),
('Ablekuma North Municipal', 8),
('Ablekuma West Municipal', 8),
('Accra Metropolitan', 8),
('Odododiodio', 8),
('Okaikwei Central', 8),
('Okaikwei South', 8),
('Ada East', 8),
('Ada West', 8),
('Adenta Municipal', 8),
('Ashaiman Municipal', 8),
('Ayawaso Central Municipal', 8),
('Ayawaso East Municipal', 8),
('Ayawaso North Municipal', 8),
('Ayawaso West Municipal', 8),
('Ga Central Municipal', 8),
('Ga East Municipal', 8),
('Ga North Municipal', 8),
('Ga South Municipal', 8),
('Domeabra-Obom', 8),
('Ga West Municipal', 8),
('Korle Klottey Municipal', 8),
('Kpone Katamanso Municipal', 8),
('Krowor Municipal', 8),
('La Dade Kotopon Municipal', 8),
('La Nkwantanang Madina Municipal', 8),
('Ledzokuku Municipal', 8),
('Ningo Prampram', 8),
('Okaikwei North Municipal', 8),
('Shai Osudoku', 8),
('Tema Metropolitan', 8),
('Tema East', 8),
('Tema West Municipal', 8),
('Weija Gbawe Municipal', 8),
('Gushegu Municipal',9),
('Karaga', 9),
('Kpandai', 9),
('Kumbungu', 9),
('Mion', 9),
('Nanton', 9),
('Nanumba North Municipal', 9),
('Nanumba South', 9),
('Saboba', 9),
('Sagnarigu Municipal', 9),
('Savelugu Municipal', 9),
('Tamale Metropolitan', 9),
('Tamale South', 9),
('Tatale Sanguli', 9),
('Tolon', 9),
('Yendi Municipal', 9),
('Zabzugu', 9),
('Bunkpurugu Nyankpanduri', 10),
('Chereponi', 10) ,
('East Mamprusi Municipal', 10),
('Mamprugu Moagduri', 10),
('West Mamprusi Municipal', 10),
('Yunyoo-Nasuan', 10),
('Bole', 11),
('Central Gonja', 11),
('East Gonja Municipal', 11),
('North East Gonja', 11),
('North Gonja', 11),
('Sawla-Tuna-Kalba', 11),
('West Gonja Municipal', 11),
('Bawku Municipal', 12),
('Bawku West', 12),
('Binduri', 12),
('Bolgatanga East', 12),
('Bolgatanga Municipal', 12),
('Bongo', 12),
('Builsa North Municipal', 12),
('Builsa South', 12),
('Garu', 12),
('Kassena Nankana Municipal', 12),
('Kassena Nankana West', 12),
('Nabdam',12),
('Pusiga',12),
('Talensi', 12),
('Tempane', 12),
('Daffiama Bussie Issa', 13),
('Jirapa Municipal', 13),
('Lambussie Karni', 13),
('Lawra Municipal', 13),
('Nadowli Kaleo', 13),
('Nandom Municipal', 13),
('Sissala East Municipal', 13),
('Sissala West', 13),
('Wa East', 13),
('Wa Municipal', 13),
('Wa West', 13),
('Adaklu District', 14),
('Afadzato South', 14),
('Agotime Ziope', 14),
('Akatsi North', 14),
('Akatsi South', 14),
('Anloga', 14),
('Central Tongu', 14),
('Ho Municipal', 14),
('Ho West', 14),
('Hohoe Municipal', 14),
('Keta Municipal', 14),
('Ketu North Municipal', 14),
('Ketu South Municipal',14),
('Kpando Municipal', 14),
('North Dayi', 14),
('North Tongu', 14),
('South Dayi', 14),
('South Tongu', 14),
('Ahanta West Municipal', 15),
('Amenfi Central', 15),
('Amenfi West Municipal', 15),
('Effia Kwesimintsim Municipal', 15),
('Ellembelle', 15),
('Jomoro Municipal', 15),
('Mpohor', 15),
('Nzema East Municipal', 15),
('Prestea-Huni Valley Municipal', 15),
('Sekondi Takoradi Metropolitan', 15),
('Shama', 15),
('Tarkwa-Nsuaem Municipal', 15),
('Wassa Amenfi East Municipal', 15),
('Wassa East', 15),
('Aowin Municipal', 16),
('Bia East', 16),
('Bia West', 16),
('Bibiani Anhwiaso Bekwai Municipal', 16),
('Bodi', 16),
('Juaboso', 16),
('Sefwi Akontombra', 16),
('Sefwi-Wiawso Municipal', 16),
('Suaman', 16);
